apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    environment: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      environment: dev
      project: self
      module: frontend
  template:
    metadata:
      name: app1
      labels:
        environment: dev
        project: self
        module: frontend
    spec:
      containers:
      - name: app1
        image: amarnadh31/app1:v1
---
apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector:
    environment: dev
    project: self
    module: frontend      
  ports:
  - name: deploy-port
    protocol: TCP
    port: 80
    targetPort: 80