apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    environment: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      environment: qa
      project: self
      module: backend
  template:
    metadata:
      name: app2
      labels:
        environment: qa
        project: self
        module: backend
    spec:
      containers:
      - name: app2
        image: amarnadh31/app2:v1
---
apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  selector:
    environment: qa
    project: self
    module: backend     
  ports:
  - name: deploy-port
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: echoserver
    annotations:
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:767397679511:certificate/9ff28f3f-bfad-457b-9b51-5cf2ec59915d
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
        alb.ingress.kubernetes.io/group.name: expense
        alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
spec:
  ingressClassName: alb
  rules:
  - host: "app1.expensemind.online"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app2
            port:
              number: 80